### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by ohickman16** [pmme/Boost#3]
How can I get rid of the book and clock because they get in my way and become items across the whole server which I do not want

**Comment by ohickman16** [comment]
I would like to get rid of the boost instructions

**Comment by pmme** [comment]
You can do this easily with multiverse inventory groups. Keep the boost world in a separate group from the other sever worlds. Then the boost items will not appear in other worlds and other world items will not appear in the boost world.

**Comment by pmme** [comment]
Continued in issue #4
