### ISSUE TITLE
Clock and Book

### ISSUE THREAD

**Issue by ohickman16** [pmme/Boost#4]
Hi, We are having issues and we are unable to get rid of your book and clock so would you be able to send a .jar file of the plugin which does not have these items.

Thank You
SoulCraft Owner

**Comment by pmme** [comment]
Hi, I do know that the inventory groups can keep Boost items in only the Boost world, so that is an option you can use and I'm happy to help you get that configured.
However I can and will make a change to make the items optional so you can disable them if you still want to.

**Comment by ohickman16** [comment]
Thank you. Send it through when complete

**Comment by ohickman16** [comment]
Also I have an idea that I would like to be implemented. Please could you
add the option where you can make it that every 10 seconds (or other time)
a platform dissapears. (We would define all platforms with a tool)

Thank You

**Comment by pmme** [comment]
@ohickman16 the options are available in the new update Version 1.14.1.
https://www.spigotmc.org/resources/boost-unique-new-minigame-1-12-1-16-4.75950/update?update=374017

If you run `/boost updateconfig` it will add the options to the YML files. You can add them manually if you like. Then you can set them to false.
