### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Creme117** [pmme/Boost#5]
Its not adding a folder for the config text please help im not very smart

**Comment by pmme** [comment]
What you should be looking for is a "Boost" folder under your "plugins" folder, so "plugins/boost".
All of the files containing gameplay settings and message text are stored in that one folder.

If you can see folders for other plugins then you're looking in the correct place. In that place, if you still can't find a "boost" folder then perhaps the plugin is not running for some reason. 

Try the "/pl" command in game and see if Boost is loaded and listed in green, which indicates it loaded okay, and not red, which would indicate it didn't load properly. 

If you can't see Boost in your "/pl" list then the Boost JAR file must not be in the plugins folder. In that case, potentially you uploaded it to the wrong folder of your server.

**Comment by pmme** [comment]
Did you get this sorted @Creme117 ?
