### ISSUE TITLE
sample map help

### ISSUE THREAD

**Issue by Menach0** [pmme/Boost#9]
hey so i downloaded the plugin and sample files, but the arenas are not working, i imported the world and put the config file in the right place but it says that the sample arenas are not properly configured

**Comment by pmme** [comment]
I haven't received a server log from you, but I tried it today on Minecraft 1.20.1 and had no problem.
I think perhaps you didn't set your world name.

A suitable procedure would be as follows:
1. Create and then stop a new server.
2. Download the sample map ZIP file and put the contents into your server's main folder.
    The ZIP contains a world named "Boost" and the Boost plugin's configuration for that world stored in the standard plugins folder.
3. Edit server.properties, find "level-name" and set it as follows:
    level-name=Boost
4. Download the latest Boost plugin and put it into the server's plugins folder.
5. Start the server.
    Boost will update the game configuration a little because the ZIP and configuration was created with an older version of Boost.
    There should be no errors, only warnings that the configuration has been updated.
6. Stop and re-start the server and there should be no warnings or errors.

Hope this helps.
